### ISSUE TITLE
Adapter AutoKeras test all datatypes

### ISSUE THREAD

**Issue by AlexanderZender** [hochschule-darmstadt/MetaAutoML#150]
Reason (Why?)
To make sure adapter AutoKeras is implemented correctly, we have to test this adapter with different datatypes (images, tabular, text,...). If there is any error, bugs should be found.

Solution (What?)
Testing in local development environment, docker environment and test automation, there are currently 2 ideas:

- Automation testing inside each adapter with sub process (start automl process) , get the auto keras-job file for testing.
- Automation testing for every adapter with AdapterScheduler.

Out of scope
None

Relation to other Issues
None

Acceptance criteria

- [x] Adapter get the correct type of dataset / the path to dataset is correct,...
- [x] Adapter raise no error.
- [x] Exported model from adapter can be used for prediction.
- [x] Automation test are correctly implemented and work as expected.

Dataset types
- [x] Tabular
- [x] Image (Bug #191 , and bug that file is too big)
- [ ] Time Series (Bug #192 )

**Comment by jnnks** [comment]
AutoKerasAdapter Integration Tests for image, text and tabular data: https://github.com/hochschule-darmstadt/MetaAutoML/pull/244

* Time Series Tests have been postponed due to https://github.com/hochschule-darmstadt/MetaAutoML/issues/192
* Tests are successful when trained model can be exported, extraction and validation are not tested yet
